name: Build and Push Docker Image to GHCR

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gdis-transcribe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Convert repo owner to lowercase
      id: prep
      run: |
        # Convert the repository owner to lowercase
        repo_owner_lc=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        echo "repo_owner_lc=$repo_owner_lc" >> $GITHUB_ENV

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.repo_owner_lc }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
